apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  labels:
    app: echoweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoweb
  template:
    metadata:
      labels:
        app: echoweb
    spec:
      containers:
      - name: myecho
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
