apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  containers:
    - name: app
      image: sixeyed/whoami:21.04
#     env:
#       - name: WHOAMI_MODE
#         value: q
