apiVersion: v1
kind: Pod
metadata: 
  name: test-pd
spec:
  containers:
  - name: test-container
    image: nginx
    ports: 
      - containerPort: 80
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
  volumes:
    - name: cache-volume 
      emptyDir: {}
#     emptyDir: 
#       medium: Memory
