apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb2
  labels:
    app: web-whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-whoami
  template:
    metadata:
      labels:
        app: web-whoami
    spec:
      containers:
      - name: myweb2
        image: sixeyed/whoami:21.04
        ports:
        - containerPort: 80
