apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-whoami
  name: myweb2
spec:
  type: ClusterIP
  ports: 
    - port: 80 
      targetPort: 80
      protocol: TCP
  selector:
    app: web-whoami

